image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - prepare
  - test

install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - npm test
